
deployments: 
  cohere_platform:
    api_key: 
#   sagemaker:
#     access_key:
#     secret_key:


# # 1 - Cohere Platform 
# COHERE_API_KEY=<API_KEY_HERE>

# # 2 - SageMaker
# SAGE_MAKER_ACCESS_KEY=<ACCESS KEY>
# SAGE_MAKER_SECRET_KEY=<SECRET KEY>
# SAGE_MAKER_SESSION_TOKEN=<SESSION TOKEN>
# SAGE_MAKER_REGION_NAME=<REGION NAME>
# SAGE_MAKER_ENDPOINT_NAME=<ENDPOINT NAME>

# # 3 - Azure
# AZURE_API_KEY=<API KEY>
# AZURE_CHAT_ENDPOINT_URL=<ENDPOINT URL>

# # 4 - Bedrock
# BEDROCK_ACCESS_KEY=<ACCESS KEY>
# BEDROCK_SECRET_KEY=<SECRET KEY>
# BEDROCK_SESSION_TOKEN=<SESSION TOKEN>
# BEDROCK_REGION_NAME=<REGION NAME>


# database:
#   url: postgresql+psycopg2://postgres:postgres@db:5432
#   # Migrate access token, used to authenticate requests to the migrate endpoint.
#   # You can generate it using some random string generator.
#   migrate_token:
# tools: 
#   python_interpreter: 
#     url: http://terrarium:8080
#   tavily: 
#     api_key: 
#   wolfram_alpha:
#     app_id:



# # DEPLOYMENTS
# # To use the Toolkit, at least one deployment must be setup, the simplest
# # being the Cohere Platform. See the README.md for more details.


# # Experimental features 
# USE_EXPERIMENTAL_LANGCHAIN=False
# USE_AGENTS_VIEW=False

# # Community features
# USE_COMMUNITY_FEATURES='True'

# # For setting up authentication, see: docs/auth_guide.md
# AUTH_SECRET_KEY=<See auth.guide.md on how to generate a secure one>
# # Required for specifying Redirect URI
# FRONTEND_HOSTNAME=http://localhost:4000

# # Google OAuth 
# GOOGLE_CLIENT_ID=<GOOGLE_CLIENT_ID>
# GOOGLE_CLIENT_SECRET=<GOOGLE_CLIENT_SECRET>

# # OpenID Connect
# OIDC_CLIENT_ID=<OIDC_CLIENT_ID>
# OIDC_CLIENT_SECRET=<OIDC_CLIENT_SECRET>
# OIDC_WELL_KNOWN_ENDPOINT=<OIDC_WELL_KNOWN_ENDPOINT>

# # compass
# COHERE_COMPASS_USERNAME=
# COHERE_COMPASS_PASSWORD=
# COHERE_COMPASS_API_URL=
# COHERE_COMPASS_PARSER_URL=

# # gdrive
# GOOGLE_DRIVE_CLIENT_ID=
# GOOGLE_DRIVE_CLIENT_SECRET=