
deployments: 
  default_deployment: cohere_platform
  enabled_deployments:
    - cohere_platform
    - sagemaker
    - azure
    - bedrock
  sagemaker:
    region_name: us-west-2
    endpoint_name: cohere-command-r
  azure: 
    endpoint_url: https://cohere-ai.azurewebsites.net
  bedrock:
    region_name: us-west-2
database:
  url: postgresql+psycopg2://postgres:postgres@db:5432
tools:
  enabled_tools:
    - wikipedia
    - search_file
    - read_document
    - toolkit_python_interpreter
    - toolkit_calculator
    - web_search
    - web_scrape
  python_interpreter: 
    url: http://terrarium:8080
  compass:
    api_url: 
    parser_url:
feature_flags: 
  # Experimental features 
  use_experimental_langchain: false
  use_agents_view: false
  # Community features
  use_community_features: true
auth:
  enabled_auth:
    - basic
  frontend_hostname: http://localhost:4000


