auth:
  google_oauth:
    client_id:
    client_secret:
  oidc:
    client_id:
    client_secret:
    well_known_endpoint:
  secret_key: 4412ce959e6d41c52518f6be190e5b6f2c06bd5d88fd3f53bec12fa35a0ce579
database:
  migrate_token:
deployments:
  azure:
    api_key:
  bedrock:
    access_key:
    secret_key:
    session_token:
  cohere_platform:
    api_key: 1M5Uwg8j9oGeLIJz9R81yd0A85jXf8bbgCwyOkAt
  sagemaker:
    access_key:
    secret_key:
    session_token:
tools:
  compass:
    password:
    username:
  google_drive:
    client_id:
    client_secret:
    developer_key:
  tavily:
    api_key: ''
  wolfram_alpha:
    app_id:
