name: Interface Tests

on:
  push:
    branches: [main]
    paths:
      - src/interfaces/coral_web/**
  pull_request: {}

jobs:
  interface_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/interfaces/coral_web

steps:
  - name: Checkout repo
    uses: actions/checkout@v3
  - name: Check coral_web is formatted
    run: pnpm format
  - name: Check coral_web can build
    run: pnpm build
