name: Python Lint

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run lint check
        uses: chartboost/ruff-action@v1
        with:
          src: './src/'
      - name: Run formatter check
        uses: chartboost/ruff-action@v1
        with:
          src: './src/'
          args: 'format --check'
